### ISSUE TITLE
Provide a means to do the opposite for extensions

### ISSUE THREAD

**Issue by guest271314** [mikewest/baseline-header#1]
Developing extensions where the default behaviour of an API is _not_ the requirement will be helpful.

We have numerous means to sandbox a browsing context, no universal means to unset some or all of the default behaviours, even in extensions.

For example, MV3 has implemented `chrome.offscreen.createDocument()`. We can use Notification API to create a notification, `await navigator.permissions.request({name: 'clipboard-write'})` state is `"granted"`, however, when we call `await navigator.clipboard.writeText(location.href)` we get a `DOMException` document is not focused error. That is baked in to the specification, however, we want to be able to disable that without necessarily filing a bug to do so; a header is one option to do that, since in MV3 extensions we have control over the reponse with `respondWith()`.

It would be much simpler if we could set document level permissions, and disable focus requirement of a document in a header.

Another useful header that would be useful is setting the `opener` of a `window`. That would alleviate a lot of intermediary steps to communicate directly from a `ServiceWorker` to an arbitrary Web page, for example use Transferable objects to transfer files, folders, etc. from extensions to Web pages the user decides default security features should be exempt from.

I think we should have the capability to undo any and all of the secuirty measures that wind up eventually becoming baked in to default vendor products - thus extension authors have to undo each hardened feature individually, instead of utilizing a single object or set of headers that can handle all default security features that the developer and user decide declaratively or programmatically they do not want to be enabled by default.

Thanks for your effort in these matters.

**Comment by mikewest** [comment]
I can totally see how this is a problem for you when developing extensions, and it seems like something the extension system should aim to address on an API-by-API basis. That said, it seems pretty far outside the scope of what I'm aiming to discuss in this repo. :)

I'd suggest filing an issue against Chromium (https://crbug.com/new) or the Web Extensions spec (https://github.com/w3c/webextensions). Those seem like more appropriate forums for this request.

Thanks for your thoughts!

**Comment by guest271314** [comment]
> That said, it seems pretty far outside the scope of what I'm aiming to discuss in this repo. :)

The message I am trying to convey here is you security-focused folks should take the time to consider the downstream impact of your efforts to harden browsers, keeping in mind at each step a way to opt-_out_ of whatever your write out and implement. That is important. If you never consider how to undo your specifications and implementations it makes it difficult for experimenters and extension developers to suggest the path to proceed, where multiple layers of discrete implementations might need to be unraveled to undo just one part of what you have done.

Chromium authors banned me from participating there. W3C banned me before that as well.

Thanks again. Have a great day.
